### ISSUE TITLE
Problem in starting Mirror instance

### ISSUE THREAD

**Issue by Ujjval-Patel** [encryptogroup/RAID-PIR#3]
While executing this command 
`python raidpir_mirror.py --ip 127.0.0.1 --port 62001 --files ../files/ --retrievemanifestfrom 127.0.0.1 --precompute` 
my terminal is throwing error saying 
`RAID-PIR mirror v0.9.4
Using RAM datastore
<type 'exceptions.TypeError'> Number of blocks must be positive
`
Now I don't know whether it's a bug or some technical error from my side anyway it would be nice if you can clarify my doubt regarding this "jigsaw piece"

**Comment by dd23** [comment]
Have you created the manifest and started the vendor as described in the README?
Is your RAM large enough to fit the files (the database) you are trying to query from?

**Comment by Ujjval-Patel** [comment]
Yes I have created vendor and my ram is sufficient enough (16 GB)

**Comment by dd23** [comment]
What parameters are you using?
Number of servers, block size, number of blocks, etc…?

**Comment by Ujjval-Patel** [comment]
I think its blocksize as you can see in the example mirror instance there is no mention of blocksize, and that is what error statement is suggesting

**Comment by dd23** [comment]
That's because the block size is set when you create the manifest, see [point 1.3 in the README](https://github.com/encryptogroup/RAID-PIR#13-setting-up-the-files-to-be-distributed).

Please have a look at the entire README and follow the steps there.

**Comment by Ujjval-Patel** [comment]
Sir, I think I was looking at the wrong error in fact in "1.3 Setting up the files to be distributed" you are getting 326 blocks while I am getting 0 blocks, and just so that we are clear in "files" directory I have placed some 'jpg' and 'pdf' of total size 4.1 MB. can you suggest any Idea. And BTW thanks for so fast responses.

**Comment by dd23** [comment]
Your manifest *must* contain the blocks corresponding to the files, otherwise you cannot distribute anyhting. Make sure that manifest is created properly and that you have more than 0 blocks. For that pass the correct directory to `raidpir_create_manifest.py`, as described in the README.

**Comment by Ujjval-Patel** [comment]
Thank you, Error fixed. But now I am getting `MemoryError: Could not allocate memory for XOR.`
, I understand you have mentioned this issue in readme.md and research paper also. but can you tell me how much memory would I actually need, right now my "files" directory contains 4.1 MB of data.

**Comment by dd23** [comment]
What did you choose as block size?
Were you able to compile the [fast XOR](https://github.com/encryptogroup/RAID-PIR#11-fast-xor)?

4.1MB of data should fit into your RAM.

**Comment by Ujjval-Patel** [comment]
4096 same as you, 
and yes first when I compiled fast XOR it was successful, now it is just confirming that fast XOR is done.
`This is not intended to be used for any serious purpose.  It is only
constructed to build the C xordatastore.   There will be a serious
version of this written later that covers more of RAID-PIR...
running build
running build_ext
`

**Comment by dd23** [comment]
The error comes from [here](https://github.com/encryptogroup/RAID-PIR/blob/master/fastsimplexordatastore.c#L695) and suggests that there is something wrong with memory allocation.
This can happen if you pass wrong values at some point, so please make sure to follow the README, or add some debugging output to print the passed parameters yourself.

**Edit:** I have looked into this, and indeed it seems that `malloc()` in `fastsimplexordatastore.c` is currently failing. 
I have not figured out why that happens, as all of this worked perfectly fine until recently…

**Comment by dd23** [comment]
I have pushed a fix for this problem in 0afd1e7b2794b20dc4d67bb0c3ed8a7834f61e87
Please pull the newest version and re-build the `fastsimplexordatastore.c` and check if it is working now.

**Comment by Ujjval-Patel** [comment]
It is showing same error as before
`MemoryError: Could not allocate memory for XOR.`

**Comment by dd23** [comment]
Did you run `python setup.py build` again and is the `fastsimplexordatastore_c.so` rebuilt?

If yes, then this requires more debugging and I cannot do that right now. 

The issue is most probably that the parameters passed to [here](https://github.com/encryptogroup/RAID-PIR/blob/master/fastsimplexordatastore.c#L689) are not interpreted correctly and thus `malloc()` tries to reserve a huge amount of memory. 
You can try to debug that yourself by changing the `fastsimpledatastore.c` accordingly.

**Comment by dd23** [comment]
I have ported the code to Python3 and in the process I have also updated some interfaces between the Python code and the C code: 62a703a5160432ce2cc479a1576efeabf3187900 
I hope this has fixed the issue. If you want, you can give the newest version a try!

**Comment by dd23** [comment]
Have you tried the newest version? Can I close this issue?

**Comment by Ujjval-Patel** [comment]
> Have you tried the newest version? Can I close this issue?

Yes, Close the Issue

**Comment by Ujjval-Patel** [comment]
> Have you tried the newest version? Can I close this issue?

Yes, we can close the Issue now.
